version: "3.8"
services:
  overpass:
    container_name: overpass
    build:
      context: ./overpass
      dockerfile: Dockerfile
    ports:
      - 12345:80
    environment:
      - OVERPASS_META=no
      - OVERPASS_MODE=init
      - OVERPASS_PLANET_URL=http://download.geofabrik.de/europe/monaco-latest.osm.bz2
      - OVERPASS_DIFF_URL=http://download.geofabrik.de/europe/monaco-updates
      - OVERPASS_UPDATE_SLEEP=3600
      - OVERPASS_USE_AREAS=false
      - OVERPASS_RULES_LOAD=-1
      - OVERPASS_STOP_AFTER_INIT=false
      - OVERPASS_USE_AREAS=true
