version: "3.8"

services:
  overpass:
    container_name: overpass
    build:
      context: ./overpass
      dockerfile: Dockerfile
    ports:
      - 12345:80
    volumes:
      - ./mounts/db:/app/db
      - ./mounts/data:/data
    environment:
      - OVERPASS_META=no
      - OVERPASS_MODE=init
      - OVERPASS_UPDATE_SLEEP=3600
      - OVERPASS_RULES_LOAD=-1
      - OVERPASS_STOP_AFTER_INIT=false
      - OVERPASS_USE_AREAS=true
    entrypoint: ["/bin/sh", "-c", "/app/api-entrypoint.sh"]

  data:
    container_name: data-service
    build:
      context: ./overpass
      dockerfile: Dockerfile
    volumes:
      - ./mounts/db:/app/db
      - ./mounts/data:/data
    environment:
      - OVERPASS_META=no
      - OVERPASS_MODE=init
      - OVERPASS_DIFF_URL=https://download.geofabrik.de/north-america/us/missouri-updates/
      - OVERPASS_UPDATE_SLEEP=3600
      - OVERPASS_USE_AREAS=false
      - OVERPASS_RULES_LOAD=-1
      - OVERPASS_STOP_AFTER_INIT=false
      - OVERPASS_USE_AREAS=true
      - TARGET_SEQUENCE_NUMBER=4237
    entrypoint: ["/bin/sh", "-c", "/app/data-entrypoint.sh"]
