apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  selector:
    app: api
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80